---
apiVersion: v1
kind: Service
metadata:
  name: minio-tenant-console-service-external
  namespace: minio
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    v1.min.io/tenant: minio-tenant
  ports:
  - name: http-console
    port: 9090
    protocol: TCP
    targetPort: 9090
