version: '3'

services:
  minio:
    image: docker.io/minio/minio:latest
    command: [ "server", "/data", "--console-address", ":9001" ]
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    environment:
      - MINIO_ROOT_USER=rhio
      - MINIO_ROOT_PASSWORD=rhio_password
      - MINIO_DEFAULT_BUCKETS=rhio

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
