apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-30"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rhio
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://HIRO-MicroDataCenters-BV.github.io/rhio/helm-charts/
    chart: rhio-operator
    targetRevision: 0.*.*
    helm:
      version: v3
      parameters:
        - name: crds
          value: "false"    
      valuesObject:
        kubernetesClusterDomain: cluster1.local
        image:
          repository: "ghcr.io/hiro-microdatacenters-bv/rhio"
          tag: "0.2.1"

  syncPolicy:  
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
