apiVersion: rhio.hiro.io/v1
kind: ReplicatedMessageStream
metadata:
  name: test-stream
  namespace: rhio
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "30"
spec:
  streamName: stream
  subjects:
    - cluster1
  