---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhio-operator-role
rules:
  - apiGroups: ["rhio.hiro.io"]  # Replace with correct API group
    resources: 
      - "rhioservices"
      - "replicatedmessagestreams"
      - "replicatedmessagestreamsubscriptions"
      - "replicatedobjectstores"
      - "replicatedobjectstoresubscriptions"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]  # Core API (for interacting with pods, services, etc.)
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhio-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhio-operator-binding
subjects:
  - kind: ServiceAccount
    name: rhio-operator-sa  # Ensure this matches your operator's ServiceAccount
    namespace: default  # Replace with your operator's namespace
roleRef:
  kind: ClusterRole
  name: rhio-operator-role
  apiGroup: rbac.authorization.k8s.io