[package]
name = "rhio"
version = "0.1.0"
edition = "2021"

[lib]
name = "rhio"

[[example]]
name = "hello"

[[example]]
name = "sync"

[dependencies]
anyhow = "1.0.86"
async-stream = "0.3.5"
ciborium = "0.2.2"
clap = { version = "4.5.8", features = ["derive"] }
# @TODO: remove after https://github.com/HIRO-MicroDataCenters-BV/rhio/issues/40 fixed 
derive_more = { version = "=1.0.0-beta.6", features = [
    "debug",
    "display",
    "deref",
    "deref_mut",
    "from",
    "try_into",
    "into",
] }
figment = { version = "0.10.19", features = ["env"] }
futures-lite = "2.3.0"
futures-util = "0.3.30"
hex = "0.4.3"
iroh-blobs = { version = "0.20.0", features = ["fs-store"], default-features = false }
num_cpus = "1.16.0"
p2panda-blobs = { path = "../p2panda-blobs" }
p2panda-core = { path = "../p2panda-core" }
p2panda-net = { path = "../p2panda-net" }
p2panda-store = { path = "../p2panda-store" }
reqwest = { version = "0.12.5", features = ["stream"] }
rust-s3 = "0.34.0"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = "0.1.15"
tokio-util = "0.7.11"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3.10.1"
notify-debouncer-full = "0.3.1"
