[package]
name = "rhio"
version = "0.1.0"
edition = "2021"
default-run = "rhio"

[lib]
name = "rhio"

[dependencies]
anyhow = "1.0.86"
async-nats = "0.35.1"
async-stream = "0.3.5"
ciborium = "0.2.2"
clap = { version = "4.5.8", features = ["derive"] }
directories = "5.0.1"
figment = { version = "0.10.19", features = ["env", "yaml"] }
futures-util = "0.3.30"
hex = "0.4.3"
iroh-blobs = { version = "0.25.0", features = ["fs-store"], default-features = false }
p2panda-blobs = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-core = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-engine = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-net = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-store = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-sync = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
rhio-core = { path = "../rhio-core" }
rust-s3 = "0.34.0"
serde = { version = "1.0.203", features = ["derive"] }
tokio = "1.38.0"
tokio-stream = "0.1.15"
tokio-util = "0.7.11"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
figment = { version = "0.10.19", features = ["env", "toml", "test"] }
