[package]
name = "rhio"
version = "0.1.0"
edition = "2021"
default-run = "rhio"

[lints]
workspace = true

[lib]
name = "rhio"

[dependencies]
anyhow = "1.0.93"
async-nats = "0.37.0"
async-trait = "0.1.83"
ciborium = "0.2.2"
clap = { version = "4.5.8", features = ["derive"] }
directories = "5.0.1"
figment = { version = "0.10.19", features = ["env", "yaml"] }
futures-util = "0.3.30"
hex = "0.4.3"
iroh-blobs = { version = "0.25.0", features = ["fs-store"], default-features = false }
loole = "0.4.0"
p2panda-blobs = { git = "https://github.com/p2panda/p2panda.git", rev = "c09d820d8a758f8894e2123180f57c1b4bb33263" }
p2panda-core = { git = "https://github.com/p2panda/p2panda.git", rev = "c09d820d8a758f8894e2123180f57c1b4bb33263" }
p2panda-net = { git = "https://github.com/p2panda/p2panda.git", rev = "c09d820d8a758f8894e2123180f57c1b4bb33263", default-features = false }
p2panda-sync = { git = "https://github.com/p2panda/p2panda.git", rev = "c09d820d8a758f8894e2123180f57c1b4bb33263", features = ["cbor"], default-features = false }
rand = "0.8.5"
rhio-blobs = { path = "../rhio-blobs" }
rhio-core = { path = "../rhio-core" }
rust-s3 = "0.35.1"
serde = { version = "1.0.209", features = ["derive"] }
tokio = "1.41.1"
tokio-stream = "0.1.15"
tokio-util = "0.7.11"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
figment = { version = "0.10.19", features = ["env", "toml", "test"] }
