[package]
name = "rhio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
figment = { version = "0.10.19", features = ["env"] }
flume = "0.11.0"
futures = "0.3.30"
futures-lite = "2.3.0"
futures-util = "0.3.30"
iroh-base = "0.20.0"
iroh-blobs = { version = "0.20.0", features = ["downloader"], default-features = false }
iroh-gossip = "0.20.0"
iroh-io = "0.6.0"
iroh-net = "0.20.0"
num_cpus = "1.16.0"
p2panda-net = {path = "../p2panda-net"}
p2panda-core = {path = "../../p2panda/p2panda-core"}
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = "0.7.11"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
hex = "0.4.3"

[dev-dependencies]
tempfile = "3.10.1"
