apiVersion: rhio.hiro.io/v1
kind: RhioService
metadata:
  name: test-service
spec:
    clusterConfig:
      listenerClass: cluster-internal
      gracefulShutdownTimeout: 1s

    image:
      custom: ghcr.io/hiro-microdatacenters-bv/rhio:1.0.0
      productVersion: 1.0.0
      pullPolicy: IfNotPresent      

    configuration:
      networkId: test
      privateKeySecret: secret-key
      nodes: []
      s3: null
      nats:
        endpoint: nats://nats-jetstream.dkg-engine.svc.cluster.local:4222
        credentials: null        
