apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/nats
patches:
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/config/serverNamePrefix
        value: cluster2.local
    target: 
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: nats-jetstream
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/config/websocket/ingress/hosts/0
        value: nats-websocket.cluster2.local
    target: 
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: nats-jetstream
      namespace: argocd