[package]
name = "rhio-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ciborium = "0.2.2"
hex = "0.4.3"
p2panda-core = { git = "https://github.com/p2panda/p2panda.git", branch = "v2" }
p2panda-store = { git = "https://github.com/p2panda/p2panda.git", branch = "v2" }
serde = { version = "1.0.209", features = ["derive"] }

[dev-dependencies]
tempfile = "3.10.1"

[lints]
workspace = true
