[package]
name = "rhio-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-nats = "0.37.0"
ciborium = "0.2.2"
constcat = "0.5.1"
hex = "0.4.3"
p2panda-core = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-engine = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-store = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
p2panda-sync = { git = "https://github.com/p2panda/p2panda.git", rev = "89489b7d1c1406bf8ead9aadbb0b5d319c922d4b" }
serde = { version = "1.0.209", features = ["derive"] }

[dev-dependencies]
tempfile = "3.10.1"
tokio = { version = "1.40.0", features = ["rt", "macros"] }

[lints]
workspace = true
