[package]
name = "rhio-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ciborium = "0.2.2"
hex = "0.4.3"
p2panda-core = { git = "https://github.com/p2panda/p2panda.git", rev = "3b9c8af7064ba489ef5eab9d4a165fab7b8c40c4" }
p2panda-store = { git = "https://github.com/p2panda/p2panda.git", rev = "3b9c8af7064ba489ef5eab9d4a165fab7b8c40c4" }
p2panda-engine = { git = "https://github.com/p2panda/p2panda.git", rev = "3b9c8af7064ba489ef5eab9d4a165fab7b8c40c4" }
serde = { version = "1.0.209", features = ["derive"] }

[dev-dependencies]
tempfile = "3.10.1"
tokio = { version = "1.40.0", features = ["rt", "macros"] }

[lints]
workspace = true
