---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-clusterrole
  labels:
  {{- include "operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  # For automatic cluster domain detection
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get      
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
      - services
      - endpoints
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - bind
    resourceNames:
      - {{ include "operator.name" . }}-clusterrole
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - create
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups: 
      - rhio.hiro.io
    resources: 
      - rhioservices
      - replicatedmessagestreams
      - replicatedmessagestreamsubscriptions
      - replicatedobjectstores
      - replicatedobjectstoresubscriptions
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - rhio.hiro.io
    resources: 
      - rhioservices/status
      - replicatedmessagestreams/status
      - replicatedmessagestreamsubscriptions/status
      - replicatedobjectstores/status
      - replicatedobjectstoresubscriptions/status
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.name" . }}-clusterrole
  labels:
  {{- include "operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - get
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
{{ if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - nonroot-v2
    verbs:
      - use
{{ end }}
